[workspace]
# Using version 2 to avoid unifying features. For more info, read:
#   https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = ["crates/committer", "crates/committer_cli"]

[workspace.package]
version = "0.1.0-rc.0"
edition = "2021"
repository = "https://github.com/starkware-libs/committer/"
license = "Apache-2.0"
license-file = "LICENSE"

[workspace.dependencies]
async-recursion = "1.1.0"
bisection = "0.1.0"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
derive_more = "0.99.17"
ethnum = "1.5.0"
hex = "0.4"
pretty_assertions = "1.2.1"
rand = "0.8.5"
rand_distr = "0.4.3"
rstest = "0.17.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.116"
starknet-types-core = { version = "0.1.2", features = ["hash"] }
starknet_api = "0.13.0-dev.5"
strum = " 0.26.2"
strum_macros = "0.26.2"
thiserror = "1.0.58"
tokio = { version = "1", features = ["full"] }

[workspace.lints.rust]
future-incompatible = "deny"
nonstandard-style = "deny"
rust-2018-idioms = "deny"
unused = "deny"
warnings = "deny"

[workspace.lints.clippy]
as_conversions = "deny"
unwrap_used = "deny"
