[package]
name = "committer"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Computes and manages Starknet state."

[lints]
workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true

[dependencies]
starknet-types-core.workspace = true
derive_more = "0.99.17"
