on:
  push:
    branches:
      - main
      - main-v[0-9]+.**
    tags:
      - v[0-9]+.**

jobs:
  gcs-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Get commit hash prefix
        id: commit_prefix
        run: echo "short_hash=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Build CLI binary
        run: cargo build -p committer_cli -r --bin committer_cli --target-dir CLI_TARGET

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.COMMITER_PRODUCTS_EXT_WRITER_JSON }}

      - name: Upload binary to GCP
        id: upload_file
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "CLI_TARGET/release/committer_cli"
          destination: "committer-products-external/merged/${{ steps.commit_prefix.outputs.short_hash }}/release/"
